// LOCALHOST
### Get all user records
GET http://localhost:8080/users

### Get all songs records
GET http://localhost:8080/songs

### Get all albums records
GET http://localhost:8080/albums

### Get all artists records
GET http://localhost:8080/artists

### Get all playlists records
GET http://localhost:8080/playlists