// LOCALHOST
### Get all user records
GET http://localhost:8080/users

### Get all user records
GET http://localhost:8080/songs

### Get all user records
GET http://localhost:8080/albums

### Get all user records
GET http://localhost:8080/artists

### Get all user records
GET http://localhost:8080/playlists