### Get all user records
GET http://localhost:8080/users

### Get all songs records
GET http://localhost:8080/songs

### Get all albums records
GET http://localhost:8080/albums

### Get all artists records
GET http://localhost:8080/artists


--------------ARTIST ROUTS--------------

### Get artist recordby Id
GET http://localhost:8080/artists/

### Get artists record by id
GET http://localhost:8080/artists/668ce61ae0e394a2e0761319

### Create artists record
POST http://localhost:8080/books HTTP/1.1
content-type: application/json

 {
  "name": "The Hardkiss",
  "bio": "The Hardkiss is a Ukrainian progressive-pop band known for their eclectic music style and striking visual performances.",
  "genre": "Progressive Pop"
}

### PUT book record
PUT http://localhost:8080/artists/667fe6d19176da6150925860 HTTP/1.1
content-type: application/json

{
  "name": "The Hardkiss Updated",
  "bio": "Updated The Hardkiss is a Ukrainian progressive-pop band known for their eclectic music style and striking visual performances.",
  "genre": "Progressive Pop Updated"
}

### DELETE book record
DELETE http://localhost:8080/artists/667fe6d19176da6150925869 HTTP/1.1

### Get all playlists records
GET http://localhost:8080/playlists

### Register a new user
POST http://localhost:8080/users/register
content-type: application/json

{
    "firstname": "Dmytro",
    "lastname": "Ivanytskyi",
    "age": 25,
    "email": "dima2@example.com",
    "password": "test",
    "bio": "Music lover from Ukraine.",
    "avatar": "https://example.com/avatars/dmytro_ivanytskyi.png"
}

### User login
POST http://localhost:8080/users/login
content-type: application/json

{
    "email": "dima2@example.com",
    "password": "test"
}

### Get authenticated user's information
GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjkyOTA0ZGE4YjI1M2E4YjhjYTQxOWQiLCJmaXJzdG5hbWUiOiJEbXl0cm8iLCJsYXN0bmFtZSI6Ikl2YW55dHNreWkiLCJhZ2UiOjI1LCJlbWFpbCI6ImRpbWEyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzIwODgyNzQ3LCJleHAiOjE3MjA4ODYzNDd9.e-NL8LHRO4dsUF72CxEq1XebUt7gplY8Xc49XLu0vPg
